myProp : WartoscUkrytazPliku
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/crypto_budget_db
    username: root
    password: 7569166

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
